### PR TITLE
RDS functions added

### PR DESCRIPTION
**Pull request by star297**
I have added some RDS functions, Station Name, RDS text and CT time.
Also changed the display layout slightly to suit.
One problem I had was to call the RDA5807_Read() more frequently, needs to be called every 10mS to capture the RDS data. I added this function call to the stm32_ub_touch_stmpe811.c file as a workaround that does the trick but not really the best way to do this, needs a better way.

rda5807m

### CODE REVIEW

**Comment by papadkostas** [comment]
Nice work!! :)
About the reading function issue it could be triggered by timer interrupt.

**Comment by star297** [comment]
I did use your RDA5807M code to build a program in Mbed a while back and added some RDS code from a Mbed program using a Si-Labs radio chip. This drove a 4Dsystems Oled display and has an IAP function to store 10 presets in the upper part of Flash on the MCU depending on Target or on a SD card as I have here.

teensy-test

Mbed now has the Disco-F429ZI board added, but no emWin library. So I went back to your program to see if I could use it. However Mbed has all the MCU peripheral drivers built in including LCD and Touch library that makes it difficult to integrate your emWin code.

I haven't gone too deep into your code, I'm assuming the Touch function was interrupt or timer driven so placed a call there. Adding a Timer interrupt could cause problems with the LCD driver if they clash unless there is some blocking. I'm 'Mbed lazy' so would have difficulty to work this out here and I did not want to make any other changes to your program.
I have some more RDS function code to do when I get some time, will add here too.  

In case anyone lands here;
In the UK RDS is used by most radio stations. The national (BBC) and larger commercial stations display play lists on RT and CT time. Depending on location you may get Station Name but no RT or CT.
Generally a signal RSSI of 30 and above will give RDS data with very stable RDS above 40. This could be improved by error correction (I can't find any code or examples to do this). CT time (if transmitted) can jump around on poor signals, it is only transmitted once on the minute change.

**Comment by papadkostas** [comment]
You did good job here, your gui looks much better than mine,
with pressets and all the stuff that are necessary.
I never used mbed, and back then when i had started this project
mbed wasnt supported for my board. Maybe its time to try it.
About the touch screen updates, its done with Systick timer.
What controller and LCD do you use here in this picture?
Looks the similar to the onboard screen of F429 Discovery.

**Comment by star297** [comment]
Its not LCD, its a 4DSystems uOled-32028 display that has a video and touch driver MCU built in, the quality is outstanding. But the problem with this display it has slow serial comms limited to 256k baud, using Ticker interrupts here can be tricky however the built in controller MCU does have some built in graphics functions. Only the buttons function was used here, otherwise the rest is made up from typical line and rectangle draw commands. The other libraries (SD card and IAP) are on Mbed.
The emWin functions are far better but would not work on this slow display.

The Disco-F429ZI was only added to Mbed a few weeks ago. ST are not known for reliable code in the past here but the addition of the Discovery boards seems to work well, no problems with the F429 libraries so far. They have also added some other Discovery boards including M7.
If you haven't' already, take a look here:

https://developer.mbed.org/platforms/

The Mbed library SRC source files for the F4 are here:
https://developer.mbed.org/users/mbed_official/code/mbed-dev/file/f082c96e7119/targets/cmsis/TARGET_STM/TARGET_STM32F4

HAL source files here:
https://developer.mbed.org/users/mbed_official/code/mbed-dev/file/f082c96e7119/targets/hal/TARGET_STM/TARGET_STM32F4

I believe most of their code is generated using ST's CUBE then modified for work in Mbed.
Only problem with the Disco-F429 is the interface MCU does not have enough Flash to contain all the platform's programming algorithms so you will need to use ST-Link to program the board. On my board I swapped the interface MCU with one from a cheap Nucleo board which gives me drag n drop programming. All the other ST boards have the larger Flash interface MCU.
With Mbed's library covering all the MCU peripheral parts, you can see why I am 'Mbed Lazy'.

My Mbed page is here, I have some RDA5807M code there too:
https://developer.mbed.org/users/star297/

Give it a try, some love it some hate it.

Paul

**Pull request merged**
